### ISSUE TITLE
Add branch projection rules to the main branch

### ISSUE THREAD

**Issue by hybridx** [associate-run-projects/jbot#1]
@gautamkrishnar Can you please add branch projection rules to the main branch and a lets fork this project to further contribution.

**Comment by gautamkrishnar** [comment]
Lets make the project public then

![Screenshot 2021-04-22 at 12 22 04 AM](https://user-images.githubusercontent.com/8397274/115606012-d099cd00-a300-11eb-9241-4de9dd06f586.png)

**Comment by hybridx** [comment]
I was thinking of making this into typescript first. @gautamkrishnar thoughts?

**Comment by gautamkrishnar** [comment]
Rules added https://github.com/associate-run-projects/jbot/settings/branch_protection_rules/20259815

**Comment by gautamkrishnar** [comment]
Your choice @hybridx 😄
